/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/callback/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback */
        get: operations["callback_api_v1_auth_callback__provider__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/link/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Link another provider to the signed-in account */
        get: operations["link_api_v1_auth_link__provider__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start sign-in with GitHub or Google */
        get: operations["login_api_v1_auth_login__provider__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End every session of this account */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sign-in providers that are configured */
        get: operations["providers_api_v1_auth_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistics and style matches for a recipe body */
        post: operations["calculate_api_v1_calc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calc/scale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scale a recipe to a new batch volume and/or brewhouse efficiency */
        post: operations["scale_api_v1_calc_scale_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/fermentables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a custom fermentable */
        post: operations["create_fermentable_api_v1_catalog_fermentables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/fermentables/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom fermentable */
        delete: operations["delete_fermentable_api_v1_catalog_fermentables__item_id__delete"];
        options?: never;
        head?: never;
        /** Edit a custom fermentable */
        patch: operations["update_fermentable_api_v1_catalog_fermentables__item_id__patch"];
        trace?: never;
    };
    "/api/v1/catalog/hops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a custom hop */
        post: operations["create_hop_api_v1_catalog_hops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/hops/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom hop */
        delete: operations["delete_hop_api_v1_catalog_hops__item_id__delete"];
        options?: never;
        head?: never;
        /** Edit a custom hop */
        patch: operations["update_hop_api_v1_catalog_hops__item_id__patch"];
        trace?: never;
    };
    "/api/v1/catalog/yeasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a custom yeast */
        post: operations["create_yeast_api_v1_catalog_yeasts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/yeasts/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom yeast */
        delete: operations["delete_yeast_api_v1_catalog_yeasts__item_id__delete"];
        options?: never;
        head?: never;
        /** Edit a custom yeast */
        patch: operations["update_yeast_api_v1_catalog_yeasts__item_id__patch"];
        trace?: never;
    };
    "/api/v1/catalog/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search fermentables, hops or yeasts */
        get: operations["list_catalog_api_v1_catalog__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile and linked providers */
        get: operations["read_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /** Delete the account and all of its data */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        /** Update display name or unit preference */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download everything the app holds about this account as JSON */
        get: operations["export_me_api_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/identities/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink a sign-in provider */
        delete: operations["unlink_identity_api_v1_me_identities__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my recipes, most recently updated first */
        get: operations["list_recipes_api_v1_recipes_get"];
        put?: never;
        /** Save a new recipe */
        post: operations["create_recipe_api_v1_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A recipe with its statistics and style matches */
        get: operations["read_recipe_api_v1_recipes__recipe_id__get"];
        /** Replace a recipe */
        put: operations["replace_recipe_api_v1_recipes__recipe_id__put"];
        post?: never;
        /** Delete a recipe */
        delete: operations["delete_recipe_api_v1_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List styles */
        get: operations["list_styles_api_v1_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Style with ranges and variants */
        get: operations["get_style_api_v1_styles__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalcResult */
        CalcResult: {
            /**
             * Notes
             * @description Assumptions and estimates the user should know about
             */
            notes: string[];
            stats: components["schemas"]["RecipeStatsOut"];
            /** Style Matches */
            style_matches: components["schemas"]["StyleMatchOut"][];
        };
        /**
         * CatalogType
         * @enum {string}
         */
        CatalogType: "fermentables" | "hops" | "yeasts";
        /** FermentableInput */
        FermentableInput: {
            /**
             * Addition
             * @enum {string}
             */
            addition: "mash" | "steep" | "boil" | "fermenter";
            /** Amount Kg */
            amount_kg: number;
            /** Color Lovibond */
            color_lovibond: number;
            /** Name */
            name: string;
            /** Ppg */
            ppg: number;
        };
        /** FermentableOut */
        FermentableOut: {
            /** Color Lovibond */
            color_lovibond: number;
            /**
             * Custom
             * @description True for the signed-in user's own entries, False for built-ins.
             */
            readonly custom: boolean;
            /**
             * Default Addition
             * @enum {string}
             */
            default_addition: "mash" | "steep" | "boil" | "fermenter";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Ppg */
            ppg: number;
            /**
             * Type
             * @enum {string}
             */
            type: "grain" | "extract" | "sugar" | "adjunct";
        };
        /** FermentableUpdate */
        FermentableUpdate: {
            /** Color Lovibond */
            color_lovibond?: number | null;
            /** Default Addition */
            default_addition?: ("mash" | "steep" | "boil" | "fermenter") | null;
            /** Name */
            name?: string | null;
            /** Ppg */
            ppg?: number | null;
            /** Type */
            type?: ("grain" | "extract" | "sugar" | "adjunct") | null;
        };
        /** FermentableWrite */
        FermentableWrite: {
            /** Color Lovibond */
            color_lovibond: number;
            /**
             * Default Addition
             * @enum {string}
             */
            default_addition: "mash" | "steep" | "boil" | "fermenter";
            /** Name */
            name: string;
            /** Ppg */
            ppg: number;
            /**
             * Type
             * @enum {string}
             */
            type: "grain" | "extract" | "sugar" | "adjunct";
        };
        /** FieldError */
        FieldError: {
            /**
             * Loc
             * @description Path to the offending field
             */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HopContributionOut */
        HopContributionOut: {
            /**
             * Estimated
             * @description True for whirlpool additions, which have no consensus formula
             */
            estimated: boolean;
            /** Ibu */
            ibu: number;
            /** Minutes */
            minutes: number;
            /** Name */
            name: string;
            /**
             * Use
             * @enum {string}
             */
            use: "boil" | "first_wort" | "whirlpool" | "dry_hop";
            /** Utilization */
            utilization: number;
        };
        /** HopInput */
        HopInput: {
            /** Alpha Pct */
            alpha_pct: number;
            /** Amount G */
            amount_g: number;
            /** Dry Hop Days */
            dry_hop_days?: number | null;
            /** Name */
            name: string;
            /** Time Min */
            time_min?: number | null;
            /**
             * Use
             * @enum {string}
             */
            use: "boil" | "first_wort" | "whirlpool" | "dry_hop";
        };
        /** HopOut */
        HopOut: {
            /** Alpha Typical Pct */
            alpha_typical_pct: number;
            /**
             * Custom
             * @description True for the signed-in user's own entries, False for built-ins.
             */
            readonly custom: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Origin */
            origin: string | null;
        };
        /** HopUpdate */
        HopUpdate: {
            /** Alpha Typical Pct */
            alpha_typical_pct?: number | null;
            /** Name */
            name?: string | null;
            /** Origin */
            origin?: string | null;
        };
        /** HopWrite */
        HopWrite: {
            /** Alpha Typical Pct */
            alpha_typical_pct: number;
            /** Name */
            name: string;
            /** Origin */
            origin?: string | null;
        };
        /** IdentityOut */
        IdentityOut: {
            /**
             * Last Login At
             * Format: date-time
             */
            last_login_at: string;
            /**
             * Linked At
             * Format: date-time
             */
            linked_at: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "github" | "google";
        };
        /** MetricMatchOut */
        MetricMatchOut: {
            /**
             * Delta
             * @description Signed distance from the nearest range edge; 0 when in
             */
            delta: number;
            /**
             * Metric
             * @enum {string}
             */
            metric: "og" | "fg" | "abv" | "ibu" | "srm";
            /** Penalty */
            penalty: number;
            /** Ranges */
            ranges: components["schemas"]["RangeOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "in" | "low" | "high";
            /** Value */
            value: number;
        };
        /** Page[FermentableOut] */
        Page_FermentableOut_: {
            /** Items */
            items: components["schemas"]["FermentableOut"][];
            /**
             * Next Cursor
             * @description Pass as ?cursor= to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        /** Page[HopOut] */
        Page_HopOut_: {
            /** Items */
            items: components["schemas"]["HopOut"][];
            /**
             * Next Cursor
             * @description Pass as ?cursor= to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        /** Page[RecipeSummary] */
        Page_RecipeSummary_: {
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
            /**
             * Next Cursor
             * @description Pass as ?cursor= to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        /** Page[StyleSummary] */
        Page_StyleSummary_: {
            /** Items */
            items: components["schemas"]["StyleSummary"][];
            /**
             * Next Cursor
             * @description Pass as ?cursor= to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        /** Page[YeastOut] */
        Page_YeastOut_: {
            /** Items */
            items: components["schemas"]["YeastOut"][];
            /**
             * Next Cursor
             * @description Pass as ?cursor= to fetch the next page; null on the last page
             */
            next_cursor: string | null;
        };
        /**
         * Problem
         * @description Problem details object (RFC 9457) with a request_id extension member.
         */
        Problem: {
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
            /** Instance */
            instance?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * Provider
         * @enum {string}
         */
        Provider: "github" | "google";
        /** ProvidersOut */
        ProvidersOut: {
            /** Providers */
            providers: ("github" | "google")[];
        };
        /** RangeOut */
        RangeOut: {
            /** Label */
            label: string | null;
            /** Max */
            max: number;
            /** Min */
            min: number;
        };
        /** RecipeFermentableInput */
        RecipeFermentableInput: {
            /**
             * Addition
             * @enum {string}
             */
            addition: "mash" | "steep" | "boil" | "fermenter";
            /** Amount Kg */
            amount_kg: number;
            /** Color Lovibond */
            color_lovibond: number;
            /**
             * Fermentable Id
             * @description Catalog row this was taken from; values are snapshots
             */
            fermentable_id?: string | null;
            /** Name */
            name: string;
            /** Ppg */
            ppg: number;
            /**
             * Type
             * @enum {string}
             */
            type: "grain" | "extract" | "sugar" | "adjunct";
        };
        /** RecipeFermentableOut */
        RecipeFermentableOut: {
            /**
             * Addition
             * @enum {string}
             */
            addition: "mash" | "steep" | "boil" | "fermenter";
            /** Amount Kg */
            amount_kg: number;
            /** Color Lovibond */
            color_lovibond: number;
            /**
             * Fermentable Id
             * @description Catalog row this was taken from; values are snapshots
             */
            fermentable_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Ppg */
            ppg: number;
            /**
             * Type
             * @enum {string}
             */
            type: "grain" | "extract" | "sugar" | "adjunct";
        };
        /** RecipeHopInput */
        RecipeHopInput: {
            /** Alpha Pct */
            alpha_pct: number;
            /** Amount G */
            amount_g: number;
            /** Dry Hop Days */
            dry_hop_days?: number | null;
            /** Hop Id */
            hop_id?: string | null;
            /** Name */
            name: string;
            /** Time Min */
            time_min?: number | null;
            /**
             * Use
             * @enum {string}
             */
            use: "boil" | "first_wort" | "whirlpool" | "dry_hop";
        };
        /** RecipeHopOut */
        RecipeHopOut: {
            /** Alpha Pct */
            alpha_pct: number;
            /** Amount G */
            amount_g: number;
            /** Dry Hop Days */
            dry_hop_days?: number | null;
            /** Hop Id */
            hop_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Time Min */
            time_min?: number | null;
            /**
             * Use
             * @enum {string}
             */
            use: "boil" | "first_wort" | "whirlpool" | "dry_hop";
        };
        /** RecipeInput */
        RecipeInput: {
            /**
             * Batch Volume L
             * @description Volume into the fermenter
             */
            batch_volume_l: number;
            /** Boil Time Min */
            boil_time_min: number;
            /**
             * Brewhouse Efficiency Pct
             * @default 72
             */
            brewhouse_efficiency_pct: number;
            /** Fermentables */
            fermentables?: components["schemas"]["FermentableInput"][];
            /** Hops */
            hops?: components["schemas"]["HopInput"][];
            /**
             * Pre Boil Volume L
             * @description Optional; only used to estimate boil gravity
             */
            pre_boil_volume_l?: number | null;
            /**
             * Steep Efficiency Pct
             * @default 50
             */
            steep_efficiency_pct: number;
            /**
             * Target Style
             * @description Slug of the style the recipe aims for
             */
            target_style?: string | null;
            /** Yeasts */
            yeasts?: components["schemas"]["YeastInput"][];
        };
        /** RecipeOut */
        RecipeOut: {
            /** Batch Volume L */
            batch_volume_l: number;
            /** Boil Time Min */
            boil_time_min: number;
            /** Brewhouse Efficiency Pct */
            brewhouse_efficiency_pct: number;
            /** Calc Notes */
            calc_notes: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fermentables */
            fermentables: components["schemas"]["RecipeFermentableOut"][];
            /** Hops */
            hops: components["schemas"]["RecipeHopOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string;
            /** Pre Boil Volume L */
            pre_boil_volume_l: number | null;
            stats: components["schemas"]["RecipeStatsOut"];
            /** Steep Efficiency Pct */
            steep_efficiency_pct: number;
            /** Style Matches */
            style_matches: components["schemas"]["StyleMatchOut"][];
            target_style: components["schemas"]["StyleSummary"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Yeasts */
            yeasts: components["schemas"]["RecipeYeastOut"][];
        };
        /** RecipeStatsOut */
        RecipeStatsOut: {
            /** Abv */
            abv: number;
            /**
             * Abv Alternate
             * @description Reported when OG > 1.070
             */
            abv_alternate: number | null;
            /** Attenuation Assumed */
            attenuation_assumed: boolean;
            /** Attenuation Pct */
            attenuation_pct: number;
            /** Boil Gravity */
            boil_gravity: number;
            /**
             * Boil Gravity Mode
             * @enum {string}
             */
            boil_gravity_mode: "og" | "average_of_pre_boil_and_og";
            /** Ebc */
            ebc: number;
            /** Fg */
            fg: number;
            /** Gravity Units */
            gravity_units: number;
            /** Hop Contributions */
            hop_contributions: components["schemas"]["HopContributionOut"][];
            /** Ibu */
            ibu: number;
            /** Mcu */
            mcu: number;
            /** Og */
            og: number;
            /** Srm */
            srm: number;
        };
        /** RecipeSummary */
        RecipeSummary: {
            /** Abv */
            abv: number;
            /** Fg */
            fg: number;
            /** Ibu */
            ibu: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Og */
            og: number;
            /** Srm */
            srm: number;
            target_style: components["schemas"]["StyleSummary"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RecipeWrite
         * @description Body for creating or replacing a recipe.
         */
        RecipeWrite: {
            /**
             * Batch Volume L
             * @description Volume into the fermenter
             */
            batch_volume_l: number;
            /** Boil Time Min */
            boil_time_min: number;
            /**
             * Brewhouse Efficiency Pct
             * @default 72
             */
            brewhouse_efficiency_pct: number;
            /** Fermentables */
            fermentables?: components["schemas"]["RecipeFermentableInput"][];
            /** Hops */
            hops?: components["schemas"]["RecipeHopInput"][];
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Pre Boil Volume L
             * @description Optional; only used to estimate boil gravity
             */
            pre_boil_volume_l?: number | null;
            /**
             * Steep Efficiency Pct
             * @default 50
             */
            steep_efficiency_pct: number;
            /**
             * Target Style
             * @description Slug of the style the recipe aims for
             */
            target_style?: string | null;
            /** Yeasts */
            yeasts?: components["schemas"]["RecipeYeastInput"][];
        };
        /** RecipeYeastInput */
        RecipeYeastInput: {
            /** Attenuation Pct */
            attenuation_pct: number;
            /** Name */
            name: string;
            /** Yeast Id */
            yeast_id?: string | null;
        };
        /** RecipeYeastOut */
        RecipeYeastOut: {
            /** Attenuation Pct */
            attenuation_pct: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Yeast Id */
            yeast_id?: string | null;
        };
        /** ScaleRequest */
        ScaleRequest: {
            /** Batch Volume L */
            batch_volume_l?: number | null;
            /** Brewhouse Efficiency Pct */
            brewhouse_efficiency_pct?: number | null;
            recipe: components["schemas"]["RecipeInput"];
        };
        /** ScaleResult */
        ScaleResult: {
            recipe: components["schemas"]["RecipeInput"];
            stats: components["schemas"]["RecipeStatsOut"];
        };
        /** SignedOutEverywhere */
        SignedOutEverywhere: {
            /** Sessions Revoked */
            sessions_revoked: number;
        };
        /** StyleDetail */
        StyleDetail: {
            /** Category Code */
            category_code: string;
            /** Category Name */
            category_name: string;
            /** Code */
            code: string | null;
            /** Display Name */
            display_name: string;
            /** Guideline */
            guideline: string;
            /** Guideline Version */
            guideline_version: string;
            /** Name */
            name: string;
            parent: components["schemas"]["StyleSummary"] | null;
            /** Parent Slug */
            parent_slug: string | null;
            /** Ranges */
            ranges: components["schemas"]["StyleRangeOut"][];
            /** Slug */
            slug: string;
            /** Source Url */
            source_url: string | null;
            /** Summary */
            summary: string;
            /** Variants */
            variants: components["schemas"]["StyleSummary"][];
        };
        /** StyleMatchOut */
        StyleMatchOut: {
            /** Code */
            code: string | null;
            /** Compared */
            compared: number;
            /** Display Name */
            display_name: string;
            /** Fits */
            fits: boolean;
            /** Metrics */
            metrics: components["schemas"]["MetricMatchOut"][];
            /** Score */
            score: number;
            /** Slug */
            slug: string;
            /** Tiebreak */
            tiebreak: number;
        };
        /** StyleRangeOut */
        StyleRangeOut: {
            /** Label */
            label: string | null;
            /** Max */
            max: number;
            /**
             * Metric
             * @enum {string}
             */
            metric: "og" | "fg" | "abv" | "ibu" | "srm";
            /** Min */
            min: number;
        };
        /** StyleSummary */
        StyleSummary: {
            /** Category Code */
            category_code: string;
            /** Category Name */
            category_name: string;
            /** Code */
            code: string | null;
            /** Display Name */
            display_name: string;
            /** Name */
            name: string;
            /** Parent Slug */
            parent_slug: string | null;
            /** Ranges */
            ranges: components["schemas"]["StyleRangeOut"][];
            /** Slug */
            slug: string;
        };
        /** UserOut */
        UserOut: {
            /** Avatar Url */
            avatar_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identities */
            identities: components["schemas"]["IdentityOut"][];
            /**
             * Unit Pref
             * @enum {string}
             */
            unit_pref: "metric" | "imperial";
        };
        /**
         * UserUpdate
         * @description Partial update: omit a field to leave it alone. Fields cannot be set to null.
         */
        UserUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Unit Pref */
            unit_pref?: ("metric" | "imperial") | null;
        };
        /** YeastInput */
        YeastInput: {
            /** Attenuation Pct */
            attenuation_pct: number;
            /** Name */
            name: string;
        };
        /** YeastOut */
        YeastOut: {
            /** Attenuation Max Pct */
            attenuation_max_pct: number;
            /** Attenuation Midpoint Pct */
            attenuation_midpoint_pct: number;
            /** Attenuation Min Pct */
            attenuation_min_pct: number;
            /**
             * Custom
             * @description True for the signed-in user's own entries, False for built-ins.
             */
            readonly custom: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lab */
            lab: string;
            /** Name */
            name: string;
            /** Product Code */
            product_code: string | null;
        };
        /** YeastUpdate */
        YeastUpdate: {
            /** Attenuation Max Pct */
            attenuation_max_pct?: number | null;
            /** Attenuation Min Pct */
            attenuation_min_pct?: number | null;
            /** Lab */
            lab?: string | null;
            /** Name */
            name?: string | null;
            /** Product Code */
            product_code?: string | null;
        };
        /** YeastWrite */
        YeastWrite: {
            /** Attenuation Max Pct */
            attenuation_max_pct: number;
            /** Attenuation Min Pct */
            attenuation_min_pct: number;
            /** Lab */
            lab: string;
            /** Name */
            name: string;
            /** Product Code */
            product_code?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_api_v1_auth_callback__provider__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect into the app; on failure to the sign-in page */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    link_api_v1_auth_link__provider__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the provider's authorization page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login_api_v1_auth_login__provider__get: {
        parameters: {
            query?: {
                next?: string | null;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the provider's authorization page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedOutEverywhere"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    providers_api_v1_auth_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    calculate_api_v1_calc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalcResult"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    scale_api_v1_calc_scale_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScaleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaleResult"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_fermentable_api_v1_catalog_fermentables_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FermentableWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FermentableOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_fermentable_api_v1_catalog_fermentables__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_fermentable_api_v1_catalog_fermentables__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FermentableUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FermentableOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_hop_api_v1_catalog_hops_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HopWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HopOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_hop_api_v1_catalog_hops__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_hop_api_v1_catalog_hops__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HopOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_yeast_api_v1_catalog_yeasts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YeastWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YeastOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_yeast_api_v1_catalog_yeasts__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_yeast_api_v1_catalog_yeasts__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YeastUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YeastOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_catalog_api_v1_catalog__kind__get: {
        parameters: {
            query?: {
                /** @description Name contains */
                q?: string | null;
                /** @description Opaque cursor from a previous page */
                cursor?: string | null;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path: {
                kind: components["schemas"]["CatalogType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FermentableOut_"] | components["schemas"]["Page_HopOut_"] | components["schemas"]["Page_YeastOut_"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    read_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    export_me_api_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    unlink_identity_api_v1_me_identities__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["Provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_recipes_api_v1_recipes_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page */
                cursor?: string | null;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecipeSummary_"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_recipe_api_v1_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    read_recipe_api_v1_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    replace_recipe_api_v1_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    delete_recipe_api_v1_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_styles_api_v1_styles_get: {
        parameters: {
            query?: {
                /** @description Name or code contains */
                search?: string | null;
                /** @description Category code, e.g. 21 */
                category?: string | null;
                /** @description Opaque cursor from a previous page */
                cursor?: string | null;
                /** @description Page size */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StyleSummary_"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_style_api_v1_styles__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleDetail"];
                };
            };
            /** @description Client error (problem details) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error (problem details) */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
